/*
 * Twilio - Api
 *
 * This is the public Twilio REST API.
 *
 * The version of the OpenAPI document: 1.37.3
 * Contact: support@twilio.com
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct ApiPeriodV2010PeriodAccountPeriodSipPeriodSipDomain {
    /// The SID of the Account that created the resource
    #[serde(rename = "account_sid", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub account_sid: Option<Option<String>>,
    /// The API version used to process the call
    #[serde(rename = "api_version", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub api_version: Option<Option<String>>,
    /// The types of authentication mapped to the domain
    #[serde(rename = "auth_type", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub auth_type: Option<Option<String>>,
    /// The RFC 2822 date and time in GMT that the resource was created
    #[serde(rename = "date_created", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub date_created: Option<Option<String>>,
    /// The RFC 2822 date and time in GMT that the resource was last updated
    #[serde(rename = "date_updated", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub date_updated: Option<Option<String>>,
    /// The unique address on Twilio to route SIP traffic
    #[serde(rename = "domain_name", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub domain_name: Option<Option<String>>,
    /// The string that you assigned to describe the resource
    #[serde(rename = "friendly_name", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub friendly_name: Option<Option<String>>,
    /// The unique string that identifies the resource
    #[serde(rename = "sid", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub sid: Option<Option<String>>,
    /// The URI of the resource, relative to `https://api.twilio.com`
    #[serde(rename = "uri", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub uri: Option<Option<String>>,
    /// The HTTP method used with voice_fallback_url
    #[serde(rename = "voice_fallback_method", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub voice_fallback_method: Option<Option<VoiceFallbackMethod>>,
    /// The URL we call when an error occurs while executing TwiML
    #[serde(rename = "voice_fallback_url", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub voice_fallback_url: Option<Option<String>>,
    /// The HTTP method to use with voice_url
    #[serde(rename = "voice_method", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub voice_method: Option<Option<VoiceMethod>>,
    /// The HTTP method we use to call voice_status_callback_url
    #[serde(rename = "voice_status_callback_method", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub voice_status_callback_method: Option<Option<VoiceStatusCallbackMethod>>,
    /// The URL that we call with status updates
    #[serde(rename = "voice_status_callback_url", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub voice_status_callback_url: Option<Option<String>>,
    /// The URL we call when receiving a call
    #[serde(rename = "voice_url", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub voice_url: Option<Option<String>>,
    /// A list mapping resources associated with the SIP Domain resource
    #[serde(rename = "subresource_uris", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub subresource_uris: Option<Option<serde_json::Value>>,
    /// Whether SIP registration is allowed
    #[serde(rename = "sip_registration", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub sip_registration: Option<Option<bool>>,
    /// Whether emergency calling is enabled for the domain.
    #[serde(rename = "emergency_calling_enabled", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub emergency_calling_enabled: Option<Option<bool>>,
    /// Whether secure SIP is enabled for the domain
    #[serde(rename = "secure", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub secure: Option<Option<bool>>,
    /// The SID of the BYOC Trunk resource.
    #[serde(rename = "byoc_trunk_sid", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub byoc_trunk_sid: Option<Option<String>>,
    /// Whether an emergency caller sid is configured for the domain.
    #[serde(rename = "emergency_caller_sid", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub emergency_caller_sid: Option<Option<String>>,
}

impl ApiPeriodV2010PeriodAccountPeriodSipPeriodSipDomain {
    pub fn new() -> ApiPeriodV2010PeriodAccountPeriodSipPeriodSipDomain {
        ApiPeriodV2010PeriodAccountPeriodSipPeriodSipDomain {
            account_sid: None,
            api_version: None,
            auth_type: None,
            date_created: None,
            date_updated: None,
            domain_name: None,
            friendly_name: None,
            sid: None,
            uri: None,
            voice_fallback_method: None,
            voice_fallback_url: None,
            voice_method: None,
            voice_status_callback_method: None,
            voice_status_callback_url: None,
            voice_url: None,
            subresource_uris: None,
            sip_registration: None,
            emergency_calling_enabled: None,
            secure: None,
            byoc_trunk_sid: None,
            emergency_caller_sid: None,
        }
    }
}

/// The HTTP method used with voice_fallback_url
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum VoiceFallbackMethod {
    #[serde(rename = "HEAD")]
    Head,
    #[serde(rename = "GET")]
    Get,
    #[serde(rename = "POST")]
    Post,
    #[serde(rename = "PATCH")]
    Patch,
    #[serde(rename = "PUT")]
    Put,
    #[serde(rename = "DELETE")]
    Delete,
}

impl Default for VoiceFallbackMethod {
    fn default() -> VoiceFallbackMethod {
        Self::Head
    }
}
/// The HTTP method to use with voice_url
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum VoiceMethod {
    #[serde(rename = "HEAD")]
    Head,
    #[serde(rename = "GET")]
    Get,
    #[serde(rename = "POST")]
    Post,
    #[serde(rename = "PATCH")]
    Patch,
    #[serde(rename = "PUT")]
    Put,
    #[serde(rename = "DELETE")]
    Delete,
}

impl Default for VoiceMethod {
    fn default() -> VoiceMethod {
        Self::Head
    }
}
/// The HTTP method we use to call voice_status_callback_url
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum VoiceStatusCallbackMethod {
    #[serde(rename = "HEAD")]
    Head,
    #[serde(rename = "GET")]
    Get,
    #[serde(rename = "POST")]
    Post,
    #[serde(rename = "PATCH")]
    Patch,
    #[serde(rename = "PUT")]
    Put,
    #[serde(rename = "DELETE")]
    Delete,
}

impl Default for VoiceStatusCallbackMethod {
    fn default() -> VoiceStatusCallbackMethod {
        Self::Head
    }
}

