/*
 * Twilio - Api
 *
 * This is the public Twilio REST API.
 *
 * The version of the OpenAPI document: 1.37.3
 * Contact: support@twilio.com
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct ApiPeriodV2010PeriodAccountPeriodMessagePeriodMessageFeedback {
    /// The SID of the Account that created the resource
    #[serde(rename = "account_sid", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub account_sid: Option<Option<String>>,
    /// The SID of the Message resource for which the feedback was provided
    #[serde(rename = "message_sid", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub message_sid: Option<Option<String>>,
    #[serde(rename = "outcome", skip_serializing_if = "Option::is_none")]
    pub outcome: Option<crate::models::MessageFeedbackEnumOutcome>,
    /// The RFC 2822 date and time in GMT that the resource was created
    #[serde(rename = "date_created", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub date_created: Option<Option<String>>,
    /// The RFC 2822 date and time in GMT that the resource was last updated
    #[serde(rename = "date_updated", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub date_updated: Option<Option<String>>,
    /// The URI of the resource, relative to `https://api.twilio.com`
    #[serde(rename = "uri", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub uri: Option<Option<String>>,
}

impl ApiPeriodV2010PeriodAccountPeriodMessagePeriodMessageFeedback {
    pub fn new() -> ApiPeriodV2010PeriodAccountPeriodMessagePeriodMessageFeedback {
        ApiPeriodV2010PeriodAccountPeriodMessagePeriodMessageFeedback {
            account_sid: None,
            message_sid: None,
            outcome: None,
            date_created: None,
            date_updated: None,
            uri: None,
        }
    }
}


