/*
 * Twilio - Api
 *
 * This is the public Twilio REST API.
 *
 * The version of the OpenAPI document: 1.37.3
 * Contact: support@twilio.com
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct ApiPeriodV2010PeriodAccountPeriodQueue {
    /// The RFC 2822 date and time in GMT that this resource was last updated
    #[serde(rename = "date_updated", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub date_updated: Option<Option<String>>,
    /// The number of calls currently in the queue.
    #[serde(rename = "current_size", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub current_size: Option<Option<i32>>,
    /// A string that you assigned to describe this resource
    #[serde(rename = "friendly_name", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub friendly_name: Option<Option<String>>,
    /// The URI of this resource, relative to `https://api.twilio.com`
    #[serde(rename = "uri", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub uri: Option<Option<String>>,
    /// The SID of the Account that created this resource
    #[serde(rename = "account_sid", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub account_sid: Option<Option<String>>,
    /// Average wait time of members in the queue
    #[serde(rename = "average_wait_time", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub average_wait_time: Option<Option<i32>>,
    /// The unique string that identifies this resource
    #[serde(rename = "sid", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub sid: Option<Option<String>>,
    /// The RFC 2822 date and time in GMT that this resource was created
    #[serde(rename = "date_created", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub date_created: Option<Option<String>>,
    /// The max number of calls allowed in the queue
    #[serde(rename = "max_size", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub max_size: Option<Option<i32>>,
}

impl ApiPeriodV2010PeriodAccountPeriodQueue {
    pub fn new() -> ApiPeriodV2010PeriodAccountPeriodQueue {
        ApiPeriodV2010PeriodAccountPeriodQueue {
            date_updated: None,
            current_size: None,
            friendly_name: None,
            uri: None,
            account_sid: None,
            average_wait_time: None,
            sid: None,
            date_created: None,
            max_size: None,
        }
    }
}


